### ISSUE TITLE
PsExec execution from memory

### ISSUE THREAD

**Issue by Derivability** [S3cur3Th1sSh1t/Get-System-Techniques#1]
You mentioned execution PsExec after loading it in memory via Invoke-ReflectivePEInjection.ps1

Could you please provide details on how to reproduce that?

In my case it throws an error:
![image](https://user-images.githubusercontent.com/44079420/131344911-3bc11e44-0630-455f-97ea-28babf94cf0d.png)

I would really appreciate if you could help me with that

UPD:

Output from your ps1 script:
![image](https://user-images.githubusercontent.com/44079420/131346079-139078b0-9efc-48c8-8f3d-cf7dc9db4c9f.png)

**Comment by S3cur3Th1sSh1t** [comment]
The in memory execution works fine. If you do that without the -s parameter it will work.
The problem is, that with the -s parameter exactly this error message from your screenshots appear. I think this is due to the psexec binary itself not being found on the file system but I didn't dig deeper into that yet.

**Comment by Derivability** [comment]
Sad. The "-s" option is the one that I need to escalate my privileges. Thank you anyway!
